### ISSUE TITLE
Feature request: prior captured image available in subsequent versions

### ISSUE THREAD

**Issue by kimbeasley** [mohamedmansour/my-hangouts-extension#103]
Feature request that when there is an upgrade to a newer version, that the old or previously captured images are available to newer updates.

**Comment by mohamedmansour** [comment]
They are available, I believe you are running two different versions (Dev/Production). You should just replace your contents of the zip folder to the dev folder. The production version doesn't interact with the dev version because they are different internal databases.

**Comment by mohamedmansour** [comment]
Persistence only lives within the same extension ID, cannot be transferred unfortunately
