### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by kimbeasley** [mohamedmansour/my-hangouts-extension#107]
Since the last updates for Google+, the plugin has not been working. All of the hangouts are not showing up that I should be able to see and the photo gallery stopped working. I use both of these on a regular basis and it would e helpful if they can be fixed before Monday. :) I tried disabling/enabling but it didn't help, I clicked on the update extensions but it didn't help, I even uninstalled/installed and it didn't work. Let me know if you need screenshots.

**Comment by mohamedmansour** [comment]
Thanks Kim, fixed in v5.0.1 8ff7a743f3ae680b9a5dea37b05dfa8b114e21e9
