### ISSUE TITLE
Endless "loading..." when 0 hangouts

### ISSUE THREAD

**Issue by duckinator** [mohamedmansour/my-hangouts-extension#113]
When there are no hangouts at all listed there (I restricted it to my circles only), it says "loading..." forever. Perhaps "No hangouts are currently active." or similar, instead?

**Comment by mohamedmansour** [comment]
We would need a better error description, or perhaps a better way to know when we are loading hmm. The thing is that when I do (/js/popup_controller.js#L81), I always show "loading..." when we have no hangouts. It should be smarter.

**Comment by duckinator** [comment]
I don't particularly understand that code (and I'm a bit busy fighting with porting a compiler to new OSes to read it thoroughly ;P) , but does the API (which, iirc is fake and you ended up having to hack  one together...) return _anything_ when there's no results? Even just an empty string?

**Comment by mohamedmansour** [comment]
Google returns an empty result when there is an error and when there are no results. I would need to do more discovery to differentiate between those two. I will see what I can do when I have time, I am still in moving (finding a home) stage :(

**Comment by duckinator** [comment]
It's alright. No major rush, just wanted to leave an issue here because I thought it was a bit silly. :P

Good luck with the move!
