### ISSUE TITLE
Add text to captures

### ISSUE THREAD

**Issue by jwill** [mohamedmansour/my-hangouts-extension#13]
User should be able to add text to captures.

Will use nubs and a background canvas for placement/compositing.

**Comment by mohamedmansour** [comment]
+1 if you can make it have MEME styles too and change of fonts/sizes/colors/etc

**Comment by jwill** [comment]
Basic text first and then fonts/colors/styles later

**Comment by mohamedmansour** [comment]
sounds great :)

**Comment by mohamedmansour** [comment]
When you have time, can you help Rayan setup his first push to GitHub? He has some stuff UI (for your stuff) that needs committing.

**Comment by jwill** [comment]
Basic text support in jwill/my-hangouts-extension master. Can add text from console.

Because you have to spawn a background canvas to apply text and that is costly, text should always be applied last.

Holding off on UI in favor of Rayan's designs.

Closing issue.
