### ISSUE TITLE
Gmail Add Group

### ISSUE THREAD

**Issue by natebb** [mohamedmansour/my-hangouts-extension#3]
There is a conflict with this extension and gmail. Whenever I try to add a group to a to, cc, or bcc field it only adds one person from the group and a comma. For me there are 6 people in the group. Once I disabled the extension the problem no longer existed.

**Comment by mohamedmansour** [comment]
I believe your talking about a different extension. This extension doesn't even interact with gmail, just talkgadget.google.com
