### ISSUE TITLE
I can't add a circle with this name "NGI" ( without quotes )

### ISSUE THREAD

**Issue by HostFat** [mohamedmansour/my-hangouts-extension#46]
As topic I can't add it from the "Circle preferences"
It doesn't show it, so it isn't selectable.

**Comment by mohamedmansour** [comment]
What happens if you wait 10-30 seconds before opening the popup? Do you see the list of circles when you click on that add section? Remember that you can only add circles that are already created, it doesn't create one for you.

**Comment by HostFat** [comment]
I see all circles, I have already added some ... I just can't see/add the one with "NGI" name
NGI circle is probably one of first circles that I have created.

Anyway, I just made another test: I changed the name of the circles to "test123" with "test" in description, and it still not available from your add-on.

**Comment by mohamedmansour** [comment]
It takes time for the circles list to populate, I believe it is within an hour, you can force it if you restart your browser. Can you try that and let me know if you see it, thanks

**Comment by HostFat** [comment]
It's still not visible.
I don't know, but if you can't find it from Google api ( or anything else that you are using ), it can be a bug from the Google side ...

**Comment by HostFat** [comment]
This bug is fixed with the last version v4.1.0
Thank you :)

**Comment by mohamedmansour** [comment]
@HostFat awesome! I found a girl last night that had a problem similar to this, and I fixed it. It turned out to be that your computer is faster than your internet causing bad requests, so I forced the session to not validate for that case. So it is a cleaner solution! 

Fixed in 4b7b657da31ba374e9a2a0170a934d5b98e2479a

Thanks for all your help :-)
