### ISSUE TITLE
Create CSS3 Tooltips for the Popup

### ISSUE THREAD

**Issue by mohamedmansour** [mohamedmansour/my-hangouts-extension#62]
This would definitely make the experience a lot better and faster to view that hidden information.

**Comment by rbouajram** [comment]
Tooltip a work in progress... expect a commit shortly

**Comment by rbouajram** [comment]
Tooltip is implemented in list of hangouts; more implementation has to be done in other areas of extension.

https://github.com/rbouajram/my-hangouts-extension/commit/10e2171cdf6af9c0d5c107307f3d309cfe89c19b
(my latest commit fixes a minor error on my part from this link)

I'll be creating a class to customize the background color soon

**Comment by mohamedmansour** [comment]
Looks great, could you merge circles and names into one tooltip? That would be pretty cool, like how you did your prototypes. If you can get that in by today, that would be awesome.
