### ISSUE TITLE
Conflict with too many searches

### ISSUE THREAD

**Issue by kimbeasley** [mohamedmansour/my-hangouts-extension#63]
While testing My Hangout 4.1.0 while having Hangout Canopy installed, I received the too many searches error. The icon kept switching from total number of hangouts to a question mark.

**Comment by ghost** [comment]
thanks.

This version queries 33% less than 4.0. I will look into the issue. Right
now, though I'm going to have some more brandy. :)

Did you see an error or just the question mark?

Thanks.

John.
On Dec 25, 2011 7:26 PM, "Kim beasley" <
reply@reply.github.com>
wrote:

**Comment by mohamedmansour** [comment]
@johnbc @kimbeasley I pushed version 4.1.1 using new updates :) It is now more results, 2x more e29b73446dad99aed67dfdf029454811c2cb3b71

**Comment by mohamedmansour** [comment]
This should be resolved by 788391c84992c83e8d2bcccbdab807e176e81b80
