### ISSUE TITLE
Enhancement: Support multiple nub groups.

### ISSUE THREAD

**Issue by jwill** [mohamedmansour/my-hangouts-extension#67]

**Comment by mohamedmansour** [comment]
Do you think this could be done by Version 5?

**Comment by jwill** [comment]
What was the timeline on the next release?

## 

James Williams
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by mohamedmansour** [comment]
whatever we would like, would be nice to release it on New Years next month January, we have these open issues:
https://github.com/mohamedmansour/my-hangouts-extension/issues?milestone=2&state=open

Dunno :) what is the complexity of this issue, I have no clue

**Comment by ghost** [comment]
what is a nub? is it like a newb?

**Comment by jwill** [comment]
It's a movable constraint. It's used for things like positioning a blur
effect or placing text.
