### ISSUE TITLE
Daynight curve in the My Hangouts map

### ISSUE THREAD

**Issue by ghost** [mohamedmansour/my-hangouts-extension#74]
Martin added  day night curve to his map map you circles extension. We should ask him to add the same feature to the My Hangouts map screen. It is pretty sweet looking.

(suggest for v5)

@mohamedmansour what do you think?

**Comment by marmat** [comment]
Sure, I could do that :-) The curve is not perfect yet, though, but I'm working on it.

By the way: I've put the unminified sources of the Overlay (+ docs and examples) in a git repo: https://github.com/kaktus621/google-maps-api-addons/tree/master/daynightoverlay

**Comment by marmat** [comment]
I thought about implementing it later in the evening as I have some time to do that today. How should the overlay be enabled? In the same way I did it in my extension (i.e. using a button next to the map type chooser), or should we use a different method to enable it (e.g. in the options screen)?
