### ISSUE TITLE
Maps API error message

### ISSUE THREAD

**Issue by kimbeasley** [mohamedmansour/my-hangouts-extension#94]
I just received a message that the Maps API has been disabled for this extension due to TOS violations. Here's the screenshot: http://screencast.com/t/Ikxob86oV

**Comment by marmat** [comment]
I can confirm that. Interestingly, this happens only in the Webstore Version (4.2.0). The Maps tab is still working in the Git Version (4.3.0).

Does anybody see what part of the TOS are meant by that message?

**Comment by mohamedmansour** [comment]
This is so weird  :( I am really disappointed in what is happening now, we are following the limits and we are caching all the locations. / @kimbeasley @kaktus621

**Comment by mohamedmansour** [comment]
@kimbeasley @kaktus621 @johnbc should we just publicly go out with this?

**Comment by marmat** [comment]
Quote by Thor Mitchell: "It appears to load the API once, and then send the same geocoding requests repeatedly thousands of times (literally)." ([source](https://plus.google.com/116805285176805120365/posts/2xRG4My7Qs6))

Let's find that evil bug, shall we? ;-)

**Comment by mohamedmansour** [comment]
I think he is referring to all the 7000 people installing this extension when a new participant joined, all 7000 are doing the geocoding request. I think we should (As martin said) use database caching, so you don't request anymore in the future. And perhaps lazy loading, only do queries when visiting maps tab.

**Comment by kimbeasley** [comment]
YEAH! I hope the database caching fixes everything.

**Comment by mohamedmansour** [comment]
This change adds webStorage to the results for locations. Hope that makes Google happy

**Comment by kimbeasley** [comment]
The error stopped.

**Comment by mohamedmansour** [comment]
@kimbeasley  The error never happened on the dev version since the extension ID differed, it only happened when we deploy it to the user. Someone is misusing our extension API and somehow intentionally causing these disruptions :(

**Comment by kimbeasley** [comment]
Wow, can you figure out who?

**Comment by mohamedmansour** [comment]
@kimbeasley only Google can :<
